version: '3'
services:
  mongo:
    image: mongo:latest
    container_name: mongo_container
    environment:
            MONGO_INITDB_ROOT_USERNAME: admin-user
            MONGO_INITDB_ROOT_PASSWORD: password
            MONGO_INITDB_DATABASE: data_base
    ports:
            - 27017:27017
    volumes:
            - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
            - ./mongorestore.sh:/docker-entrypoint-initdb.d/mongorestore.sh
            - ./db-dump:/db-dump
    networks:
      - practica_net
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
      container_name: backend_container
      ports:
      - 3000:3000
      depends_on:
        - mongodb
      command: ["./wait-for-it.sh", "mongodb:27017", "--", "npm", "start"]
      networks:
      - practica_net
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      container_name: frontend_container
      ports:
      - '80:80'
      networks:
      - practica_net
  mongo-express:
    image: mongo-express
    container_name: adminMongo_container
    depends_on:
      - mongo
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: <admin-user>
      ME_CONFIG_MONGODB_ADMINPASSWORD: <admin-password>
      ME_CONFIG_MONGODB_SERVER: mongo
    networks:
      - practica_net
  loadbalancer:
    image: nginx
    container_name: loadbalancer_container
    ports:
      - '8080:80'
    volumes:
      - ./loadbalancer/nginx.conf:/etc/nginx/nginx.conf
    command: ["nginx", "-g", "daemon off;"]
    networks:
      - practica_net